# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql:8.0
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 0841234378@Jayza
      MYSQL_USER: khajornsakDEVApp
      MYSQL_PASSWORD: 0841234378@Jayza
      MYSQL_NAME: khajornsakDEVdb
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - "sqldata:/var/lib/mysql"

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
volumes:
  sqldata: 