# Generated by Django 4.1.2 on 2022-10-14 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Programming languages', 'pl'), ('Framework', 'fw'), ('Other', 'ot')], default='Other', max_length=255)),
                ('score', models.FloatField()),
            ],
        ),
    ]
