# Generated by Django 4.1.2 on 2022-10-14 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khajornsakDEVApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='type',
            field=models.CharField(choices=[('Programming languages', 'Programming languages'), ('Framework', 'Framework'), ('Other', 'Other')], default='Other', max_length=255),
        ),
    ]
