# Generated by Django 4.1.2 on 2022-10-14 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khajornsakDEVApp', '0002_alter_skill_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='score',
            field=models.IntegerField(),
        ),
    ]
